- hosts: localhost
  vars:
  - key: "{{ keyname }}"  
  - type: "{{ inst_type }}"
  - region_name: "{{ regionname }}"
  - vol_type: "{{ voltype }}"
  - vol_size: "{{ volsize }}"
  - az: "{{ AZ }}"  
 
  tasks: 
  - name: Lauching ec2 instance
    ec2: 
      key_name: "{{ key }}"
      group_id: 'sg-041482d29f68b5ade'
      instance_type: "{{ type }}"
      image: 'ami-0ebc1ac48dfd14136'
      region: "{{ region_name }}"
      zone: "{{ az }}"
      wait: yes
      instance_tags:
        name: 'Task'
      count: 1
      vpc_subnet_id : 'subnet-d9f5cfb1'  
      assign_public_ip: yes
    register: ec2 
  - name: Creating Vol
    ec2_vol:
      instance: "{{ item.id }}"
      device_name: "/dev/xvdf"
      region: "{{ region_name }}"
      volume_size: "{{ vol_size }}"
      volume_type: "{{ vol_type }}"
    with_items: "{{ ec2.instances }}"
    register: ec2_vol
  - name: Refresh Inventory
    meta: refresh_inventory
      
- hosts: tag_name_Task
  tasks:  
  - name: Install http 
    package: 
      name: "httpd"
      state: present
  - name: Create partition
    parted:
      device: /dev/xvdf
      number: 1
      state: present
  - name: Add filesystem
    filesystem:
      fstype: ext4
      dev: /dev/xvdf1
  - name: Mount DVD read-only
    mount:
      path: /var/www/html
      src: /dev/xvdf1
      fstype: ext4
      state: mounted
  - name: Save webpage
    copy:
      src: index.html
      dest: /var/www/html
      mode: u=rw,g=r,o=r
  - name: Start httpd service
    service:
      name: "httpd" 
      state: started

      






      


